<?php

/**
 * Disable google analytics.
 */
function ulf_aalborg_settings_install() {
  // Disable googleanalytics.
  $module_disable = array(
    'googleanalytics',
  );

  module_disable($module_disable);
}

/**
 * Implements hook_update_N().
 */
function ulf_aalborg_settings_update_7001(&$sandbox)
{
  $module_enable = array(
    'sharedemail',
  );
  module_enable($module_enable);
  cache_clear_all();
}
